"""Filesystem layout helpers for study data.

Each session's CSVs are stored under:

    data/<TestType>/Raw data/<ParticipantID>/...

Where <TestType> is the part of the test type's name before the first colon
(e.g. "Test 1: Pressure data gathering" → "Test 1") sanitised for filesystem
use. Falls back to "Untitled" if the test type has no name.

Example tree::

    data/
      Test 1/
        Raw data/
          P01/
            P01_imu_R.csv
            P01_imu_L.csv
          P02/
            ...
        (Cleaned data/, Analysis/, etc. — researcher-managed, app never writes here)
      Test 3/
        Raw data/
          P05/
            P05_imu_R.csv
            P05_imu_L.csv
            P05_pressure.csv
            P05_merged.csv
            P05_merged_calibration.csv
            P05_merged_condition_1.csv
      Summary.xlsx          (generated by the app)
      gait_study.db         (SQLite, this app's database)
"""
from __future__ import annotations
import re
from pathlib import Path

from config import DATA_DIR


def _safe(component: str) -> str:
    """Strip filesystem-unsafe characters from a path component."""
    cleaned = re.sub(r"[^A-Za-z0-9 _-]", "_", component).strip()
    return cleaned or "Untitled"


def test_type_folder_name(test_type_name: str | None) -> str:
    """Derive a friendly folder name from a test type's display name.

    "Test 1: Pressure data gathering" → "Test 1"
    "Custom" → "Custom"
    None → "Untitled"
    """
    if not test_type_name:
        return "Untitled"
    short = test_type_name.split(":", 1)[0].strip()
    return _safe(short or test_type_name)


def session_raw_folder(session: dict, base: Path | None = None) -> Path:
    """Return the per-session folder where raw CSVs should be written.

    Creates intermediate directories on demand. The session dict must have
    `test_type_name` and `participant_id`.
    """
    base = base or DATA_DIR
    folder = (
        base
        / test_type_folder_name(session.get("test_type_name"))
        / "Raw data"
        / _safe(session.get("participant_id", "unknown"))
    )
    folder.mkdir(parents=True, exist_ok=True)
    return folder


def session_processed_folder(session: dict, base: Path | None = None) -> Path:
    """Currently the same as the raw folder — the merged CSV lives next to its
    inputs. The user adds Analysis/ subfolders themselves as needed; the app
    never writes to those."""
    return session_raw_folder(session, base)
